### ISSUE TITLE
[RFE] Ability to configure various libvirt provisioner parameters

### ISSUE THREAD

**Issue by br0ziliy** [purpleidea/oh-my-vagrant#121]
This annoys for a long time, time to do something about it :)
I'm using quite some storage pools in my libvirt setup, and I always have to change https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L1526 manually to use different storage pools.
Now, I'm thinking of having something like this in `omv.yaml`:
```yaml
:provisioner_options:
  :libvirt:
    - driver: kvm
      graphics_type: spice
      video_type: qxl
      connect_via_ssh: false
      username: root
      storage_pool_name: default
  :virtualbox:
    - ...
```

This is quite big change and before diving deep I'd like to have another opinion if it's worth it to do it like this, or I just have to introduce another variable `libvirt_storage_pool` and be done with it?
